name: Download Milvus x86 Image
on: workflow_dispatch # 允许手动触发

jobs:
  download-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Pull x86_64 Image
        run: docker pull --platform linux/amd64 milvusdb/milvus:v2.4.15
      
      - name: Save Image to Tar
        run: docker save milvusdb/milvus:v2.4.15 -o milvus-amd64.tar
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: milvus-amd64-tar
          path: milvus-amd64.tar
