name: Download Milvus ARM Image
on: workflow_dispatch # 允许手动触发
jobs:
  download-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Pull ARM64 Image
        run: docker pull --platform linux/arm64 milvusdb/milvus:v2.4.15
      - name: Save Image to Tar
        run: docker save milvusdb/milvus:v2.4.15 -o milvus-arm64.tar
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: milvus-arm64-tar
          path: milvus-arm64.tar
